#:schema https://rlbot.org/schemas/agent.json
[settings]
name = "Nexto (Toxic!)"
loadout_file = "loadout.toml"
run_command = "uv run toxic.py"
agent_id = "rlgym/nexto-toxic"

[details]
description = "Nexto, but angry"
fun_fact = "No Fun Allowed"
source_link = "https://github.com/Rolv-Arild/Necto"
developer = "The Collective Hatred of the Rocket League Community"
language = "rlgym"
tags = ["1v1", "teamplay", "rumble", "heatseeker", "memebot"]
